# Generated by Django 4.2.4 on 2023-08-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_servicehashtag_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service', verbose_name='Сервис'),
        ),
    ]
