# Generated by Django 4.2.4 on 2023-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_serviceprofile_document_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprofile",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
