# Generated by Django 4.2.4 on 2023-08-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_serviceprofile_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_username", models.CharField(max_length=150)),
                ("fullname", models.CharField(max_length=255)),
                ("tg_chat_id", models.BigIntegerField()),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
    ]
