# Generated by Django 4.2.4 on 2023-09-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_simpleuserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок заявки')),
                ('body', models.TextField(verbose_name='Описание заявки')),
                ('username', models.CharField(help_text='Username пользователя бота который оставил заявку', max_length=255, verbose_name='Username')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='api.service', verbose_name='Сервис')),
            ],
        ),
    ]
