# Generated by Django 4.2.4 on 2023-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='chat_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
