# Generated by Django 4.2.4 on 2023-09-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_serviceprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprofile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_services', to='api.service', verbose_name='Сервис'),
        ),
    ]
